# Generated by Django 3.2.4 on 2021-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='quantity',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
