# Generated by Django 3.2.4 on 2021-07-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='my comments'),
        ),
    ]
